name: "Tuya Doorbell Bridge"
version: "1.0.3"
slug: "tuya_doorbell"
description: "Bridge pro lokální Tuya zvonek"
url: "https://github.com/nimda95/hass-tuya-doorbell-notification"
arch:
  - aarch64  # RPI 4 je 64bit
  - armv7
startup: application
options:
  tuya_device_id: ""
  tuya_local_key: ""
  tuya_device_ip: ""
  webhook_url: ""
schema:
  tuya_device_id: str
  tuya_local_key: str
  tuya_device_ip: str
  webhook_url: str