name: "Tuya Doorbell Bridge"
version: "1.0.6"
slug: "tuya_doorbell"
description: "Bridge pro lokální Tuya zvonek"
host_network: true
arch:
  - aarch64
  - amd64
  - armv7
startup: application
options:
  tuya_device_id: ""
  tuya_local_key: ""
  tuya_device_ip: ""
  webhook_url: ""
schema:
  tuya_device_id: str
  tuya_local_key: str
  tuya_device_ip: str
  webhook_url: str